<a href="https://colab.research.google.com/github/alimoorreza/CS181-fall26-notes/blob/main/day04_mlp_for_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CS181: Computer Vision, Fall 2026**
## **Multilayer Perceptron (MLP) using PyTorch**

![MLP architecture](https://raw.githubusercontent.com/alimoorreza/CS181-fall26-notes/main/images/simple_mlp.drawio.svg)
<!--div>
    <img src="https://raw.githubusercontent.com/alimoorreza/CS181-fall26-notes/main/images/mlp.drawio.png" width="800"/>
</div-->


In [ ]:
# import torch library
import torch
import numpy as np
import torch.nn as nn


## **Question 0.1: Create an MLP with four layers connected one after the other, following these specifications:**


> The first layer has 2 input nodes and 4 output nodes.

> The second layer takes 4 input nodes and outputs 8 nodes.

> The third layer connects 8 input nodes to 16 output nodes.

> The final layer connects 16 input nodes to 2 output nodes.

**Each layer, except the last one, should use the *ReLU()* activation function for its output nodes.**

In [2]:
# import torch library
import torch
import numpy as np
import torch.nn as nn

torch.manual_seed(2)                    # for reproducibility
# construction of a linear layer
my_simple_mlp = nn.Sequential(
                          nn.Linear(2, 4),
                          nn.ReLU(),
                          nn.Linear(4, 8),
                          nn.ReLU(),
                          nn.Linear(8, 16),
                          nn.ReLU(),
                          nn.Linear(16, 2)
)

print(my_simple_mlp)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=16, bias=True)
  (5): ReLU()
  (6): Linear(in_features=16, out_features=2, bias=True)
)


##**Question 0.2: Display the weights the first, second, and third layer of your MLP.**

In [18]:
index = 6
my_simple_mlp[index].weight.data

tensor([[ 0.0711, -0.1355,  0.1015,  0.1912, -0.1650, -0.1559, -0.1039, -0.2140,
         -0.0287,  0.1557,  0.0936, -0.0806, -0.0310, -0.1087, -0.2018, -0.0682],
        [ 0.0173, -0.1268, -0.1873,  0.0730,  0.0368, -0.0778,  0.0685,  0.2311,
          0.0137, -0.1713,  0.2312,  0.1799, -0.0239, -0.1129, -0.1055,  0.2180]])

In [ ]:
# the weights of the first layer
print(f'Weights of the first layer: \n{my_simple_mlp[0].weight.data}')

# the biases of the first layer
print(f'Biases of the first layer:  \n{my_simple_mlp[0].bias.data}\n\n')

# total number of parameters in the first layer
weight_matrix_param_first_layer     = my_simple_mlp[0].weight.data.shape[0]*my_simple_mlp[0].weight.data.shape[1]
bias_param_first_layer              = my_simple_mlp[0].bias.data.shape[0]
total_param_first_layer             = weight_matrix_param_first_layer + bias_param_first_layer
print(f"Total number of parameters (first layer):", total_param_first_layer)

Weights of the first layer: 
tensor([[ 0.1622, -0.1683],
        [ 0.1939, -0.0361],
        [ 0.3021,  0.1683],
        [-0.0813, -0.5717]])
Biases of the first layer:  
tensor([ 0.1614, -0.6260,  0.0929,  0.0470])


Total number of parameters (first layer): 12


In [ ]:
# the weights of the second layer
print(f'Weights of the second layer: \n{my_simple_mlp[2].weight.data}')

# the biases of the second layer
print(f'Biases of the second layer:  \n{my_simple_mlp[2].bias.data}\n\n')

# total number of parameters in the second layer
weight_matrix_param_second_layer    = my_simple_mlp[2].weight.data.shape[0]*my_simple_mlp[2].weight.data.shape[1]
bias_param_second_layer             = my_simple_mlp[2].bias.data.shape[0]
total_param_second_layer            = weight_matrix_param_second_layer + bias_param_second_layer
print(f"Total number of parameters (second layer):", total_param_second_layer)

Weights of the second layer: 
tensor([[-0.1099,  0.4088,  0.0334,  0.2073],
        [ 0.2116, -0.2950, -0.1922,  0.4809],
        [-0.4897, -0.0340, -0.0396,  0.3547],
        [-0.0475,  0.1317, -0.0240, -0.2800],
        [-0.2834, -0.2429, -0.4542, -0.3245],
        [ 0.1177,  0.3291,  0.0246, -0.2292],
        [ 0.2197, -0.1919, -0.1108, -0.2741],
        [-0.1570, -0.4633,  0.2133,  0.1944]])
Biases of the second layer:  
tensor([0.0993, 0.2455, 0.2119, 0.0221, 0.0530, 0.0382, 0.2668, 0.3359])


Total number of parameters (second layer): 40


In [ ]:
# the weights of the third layer
print(f'Weights of the third layer: \n{my_simple_mlp[4].weight.data}')

# the biases of the third layer
print(f'Biases of the third layer:  \n{my_simple_mlp[4].bias.data}\n\n')

# total number of parameters in the third layer
weight_matrix_param_third_layer    = my_simple_mlp[4].weight.data.shape[0]*my_simple_mlp[4].weight.data.shape[1]
bias_param_third_layer             = my_simple_mlp[4].bias.data.shape[0]
total_param_third_layer            = weight_matrix_param_third_layer + bias_param_third_layer
print(f"Total number of parameters (third) layer):", total_param_third_layer)

Weights of the third layer: 
tensor([[ 0.2539,  0.2049, -0.0862, -0.0157, -0.0718,  0.2057,  0.0393,  0.3272],
        [ 0.1793, -0.3022,  0.1034,  0.3397,  0.3140, -0.0056,  0.1173, -0.3317],
        [-0.1127,  0.1724, -0.3221,  0.3080, -0.2325,  0.1118, -0.0134,  0.0623],
        [ 0.0343, -0.3305, -0.0759, -0.2235,  0.3006, -0.0434, -0.3520,  0.0856],
        [ 0.1535, -0.1583, -0.0332,  0.1528, -0.2200, -0.1869, -0.0341, -0.2483],
        [ 0.2173,  0.0289,  0.2115,  0.1893, -0.2725, -0.2204, -0.2418, -0.1136],
        [-0.1292, -0.0570, -0.3420,  0.1493,  0.2006,  0.1121,  0.2247,  0.2656],
        [-0.3490,  0.0534,  0.3280, -0.2562, -0.1574, -0.0186, -0.2199, -0.0666],
        [-0.0522,  0.3150, -0.0222,  0.1917,  0.2589,  0.1575, -0.3075,  0.2650],
        [ 0.2332, -0.2534, -0.1261,  0.2406, -0.3437, -0.3099, -0.2396,  0.1102],
        [-0.1444, -0.3153,  0.1370,  0.1788,  0.1324, -0.3029,  0.3443, -0.0267],
        [-0.3365, -0.0532,  0.2309,  0.1628, -0.0038,  0.2492, -0.322

In [ ]:
# Print the weights of the final layer
print(f'Weights of the final layer: \n{my_simple_mlp[6].weight.data}')

# Print the biases of the final layer
print(f'Biases of the final layer:  \n{my_simple_mlp[6].bias.data}\n\n')

# total number of parameters in the final layer
weight_matrix_param_final_layer    = my_simple_mlp[6].weight.data.shape[0]*my_simple_mlp[6].weight.data.shape[1]
bias_param_final_layer             = my_simple_mlp[6].bias.data.shape[0]
total_param_final_layer            = weight_matrix_param_final_layer + bias_param_final_layer
print(f"Total number of parameters (final layer):", total_param_final_layer)

Weights of the final layer: 
tensor([[ 0.0711, -0.1355,  0.1015,  0.1912, -0.1650, -0.1559, -0.1039, -0.2140,
         -0.0287,  0.1557,  0.0936, -0.0806, -0.0310, -0.1087, -0.2018, -0.0682],
        [ 0.0173, -0.1268, -0.1873,  0.0730,  0.0368, -0.0778,  0.0685,  0.2311,
          0.0137, -0.1713,  0.2312,  0.1799, -0.0239, -0.1129, -0.1055,  0.2180]])
Biases of the final layer:  
tensor([ 0.1306, -0.1286])


Total number of parameters (final layer): 34


In [ ]:
# total number of parameters in the entire MLP

total_parameters =   total_param_first_layer + \
                            total_param_second_layer + \
                            total_param_third_layer + \
                            total_param_final_layer

print(f"Total number of parameters (the full network MLP):", total_parameters)
print(f"If our computer uses a standard single-precision floating-point number for each parameter, then each parameter occupies 4 bytes (32 bits) of memory.")
print(f"Hence, our computer needs to reserve 4*{total_parameters}={4*total_parameters} bytes of memory for this network.")
print(f"One kilobytes=1000 bytes")
print(f"One megabytes=1000 kilobytes")
print(f"One megabytes=1000*1000 bytes")
print(f"Hence, our computer needs to reserve 4*{total_parameters}/1000000={(4*total_parameters)/1000000} megabytes of memory for this network.")


Total number of parameters (the full network MLP): 230
If our computer uses a standard single-precision floating-point number for each parameter, then each parameter occupies 4 bytes (32 bits) of memory.
Hence, our computer needs to reserve 4*230=920 bytes of memory for this network.
One kilobytes=1000 bytes
One megabytes=1000 kilobytes
One megabytes=1000*1000 bytes
Hence, our computer needs to reserve 4*230/1000000=0.00092 megabytes of memory for this network.


## **Question 0.3: Generate a random input for your MLP.**

In [ ]:
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)
# Let's generate one random samples of (x1, x2) for the above linear network
# We want to create only one input sample
# ---> x1 = 1

# Recall that our network's first layer has 2 input neurons. hence our input should have 2 values
# ---> x2 = 2

# We can create a random matrix with a size of (1, 2). In other words we do the following:
# number_of_samples     = 1
# random_input              = torch.randn(number_of_samples, num_of_neurons_input_layer)             # you could imagine that these are pairs of (x1, x2) as shown in the above table

random_input            = torch.randn( (1,2) )


print(f'input numbers: \n{random_input.numpy()}\n')



input numbers: 
[[ 0.39229682 -0.22356401]]



## **Question 0.4: Perform a forward pass of the input vector through your MLP.**


In [ ]:
# perform the forward pass through the network
output                = my_simple_mlp(random_input)
print(f'output layer values: \n{output.data.numpy()}\n')
print(f'size of the output: \n{output.data.shape}\n')



output layer values: 
[[ 0.13114016 -0.1286813 ]]

size of the output: 
torch.Size([1, 2])



## **Group activity: Create an MLP as shown below, consisting of three layers connected sequentially, following the specified architecture. Then generate a random input for the MLP and pass it through the network. Finally, calculate the total number of parameters in the MLP.**


> The first layer has 9216 input nodes and 4096 output nodes.

> The second layer takes 4096 input nodes and outputs 4096 nodes.

> The final layer connects 4096 input nodes to 1000 output nodes.


**Each layer, except the last one, should use the *ReLU()* activation function for its output nodes.**

![MLP architecture](https://raw.githubusercontent.com/alimoorreza/CS181-fall26-notes/main/images/mlp.drawio.png)
<!--div>
    <img src="https://raw.githubusercontent.com/alimoorreza/CS181-fall26-notes/main/images/mlp.drawio.png" width="800"/>
</div-->


In [ ]:
# your code
# ...
# ...
# ...